Repository magx2/shipkit-workshop-2, pull requests merged in 2019-02, with the labels that each got.

#8 #3 Support floating points
  src/main/java/com/example/shipkitworkshop/MathUtils.java
Labels: new feature

#9 #4 Adding junit
  src/test/java/com/example/shipkitworkshop/MathUtilsTest2.java
Labels: quality

#10 Add README.md
  README.md
Labels: docs
